on: push
name: Run phpunit testsuite
jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: mattiasgeniar/php73

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Install composer dependencies
      run: |
        composer install --prefer-dist --no-scripts -q -o;
    - name: Prepare Laravel Application
      run: |
        cp .env.ci .env
        php artisan key:generate
        mkdir -p database
        touch database/database.sqlite
        php artisan migrate
    - name: Run Testsuite
      run: vendor/bin/phpunit tests/
    - name: Run CS Fixer
      run: vendor/bin/php-cs-fixer fix
